apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopping-cart
  name: shopping-cart
  namespace: shopping-cart-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: docker.io/vijayvepa/shopping-cart-service:latest
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          livenessProbe:
            httpGet:
              path: /alive
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          ports:
            - name: management
              containerPort: 10558
              protocol: TCP
            - name: http
              containerPort: 10080
              protocol: TCP
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 2
              memory: 1024Mi
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: shopping-cart-1
subjects:
  - kind: User
    name: system:serviceaccount:shopping-cart-1:default
roleRef:
  kind: Role
  name: pod-reader