apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-db-scripts  # Sets Deployment name
  namespace: shopping-cart-with-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-db-scripts
  template:
    metadata:
      labels:
        app: init-db-scripts
    spec:
      containers:
        - image: postgres:10.1 # Sets Image
          name: init-db
          # noinspection SpellCheckingInspection
          command: [ "bin/sh", "-c", "set -x && sleep 30 && export PGPASSWORD=$DB_PASSWORD && psql --dbname=postgresdb --host=postgres --port=$POSTGRES_SERVICE_PORT --username=$DB_USER --no-password  -a -f /sqlCommands/create_tables.sql" ]
          #command: [ "bin/sh", "-c", "echo sleep 200000 && sleep 200000" ]
          volumeMounts:
            - name: create-tables
              mountPath: /sqlCommands
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_URL
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 1
              memory: 1024Mi
      volumes:
        - name: create-tables
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: create-tables
