apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: shopping-cart-with-kafka

spec:
  ports:
    - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: shopping-cart-with-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT_1
              value: 10.98.86.167:2181
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "$(ZOOKEEPER_SERVICE_SERVICE_HOST):$(ZOOKEEPER_SERVICE_SERVICE_PORT)"

            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker:9092
          image: wurstmeister/kafka:2.13-2.7.0
          imagePullPolicy: IfNotPresent
          name: kafka-broker
          ports:
            - containerPort: 9092